SELECT 
    YEAR(o.SALES_DATE) AS YEAR,
    MONTH(o.SALES_DATE) AS MONTH,
    COUNT(DISTINCT o.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT o.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE '2021%'), 1) AS PURCHASED_RATIO
FROM 
    USER_INFO u
JOIN 
    ONLINE_SALE o ON u.USER_ID = o.USER_ID
WHERE 
    u.JOINED LIKE '2021%'
GROUP BY 
    YEAR, 
    MONTH
ORDER BY 
    YEAR, 
    MONTH;